### ISSUE TITLE
atom-ide-ui not recognized in Nuclide bundle

### ISSUE THREAD

**Issue by ermik** [liuderchi/ide-yaml#34]
atom-ide-ui is bundled with Nuclide IDE, but this package keeps displaying a warning prompting to install it

This package should recognize Nuclide as satisfying atom-ide-ui dependency

**Comment by liuderchi** [comment]
@ermik Thanks for your feedback

Would you please take a screenshot of the warning prompt?
Does other ide-X packages also show warning prompt?

**Comment by ermik** [comment]
![image](https://user-images.githubusercontent.com/229435/44608890-8b294880-a7c3-11e8-9960-e359e0a375f4.png)

This is an `ide-yaml` specific error, no other errors.

**Comment by liuderchi** [comment]
@ermik I created a PR with another button to ignore such message forever

![demo1-with-tooltip](https://user-images.githubusercontent.com/4994705/44614766-f5da9280-a85c-11e8-8dd6-a7f04f2901c8.png)

**Comment by liuderchi** [comment]
@ermik [ide-yaml@0.4.4](https://atom.io/packages/ide-yaml) is out
