### ISSUE TITLE
ide-yaml install fail

### ISSUE THREAD

**Issue by dino13** [liuderchi/ide-yaml#5]
Hi guys, just trying to get this installed in atom. Getting errors. I can't seem to find the file that it says to include. Any ideas? Thanks!

Installing “ide-yaml@0.2.0” failed.Hide output…

> ide-yaml@0.2.0 install C:\Users\DPERSA~1\AppData\Local\Temp\apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr\node_modules\ide-yaml
> napa

> ide-yaml@0.2.0 postinstall C:\Users\DPERSA~1\AppData\Local\Temp\apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr\node_modules\ide-yaml
> ./build-yaml-lang-server.sh

info cache https://github.com/redhat-developer/yaml-language-server/archive/0.0.1.zip into yaml-language-server
'.' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\DPERSA~1\AppData\Local\Temp\apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr\package.json'
npm WARN apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr No description
npm WARN apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr No repository field.
npm WARN apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr No README data
npm WARN apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\dpersakis\\AppData\\Local\\atom\\app-1.21.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\dpersakis\\AppData\\Local\\atom\\app-1.21.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\dpersakis\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\dpersakis\\.atom\\.apmrc" "install" "C:\\Users\\DPERSA~1\\AppData\\Local\\Temp\\d-11794-10348-1383y1m.finhebqpvi\\package.tgz" "--runtime=electron" "--target=1.6.9" "--arch=ia32" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! ide-yaml@0.2.0 postinstall: `./build-yaml-lang-server.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ide-yaml@0.2.0 postinstall script './build-yaml-lang-server.sh'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ide-yaml package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./build-yaml-lang-server.sh
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ide-yaml
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ide-yaml
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\DPERSA~1\AppData\Local\Temp\apm-install-dir-11794-10348-v40d0s.o4gq9cc8fr\npm-debug.log

**Comment by liuderchi** [comment]
@dino13 It looks like a path issue. What's your Operation System?

**Comment by dino13** [comment]
Yes I'm on a Windows 10 machine.

**Comment by liuderchi** [comment]
@dino13 there are still some issues for this bug, please wait for a while.
I will comment here if there is patch update

**Comment by dino13** [comment]
Thank you

**Comment by liuderchi** [comment]
Sorry, accidentally close this issue. It's not solved yet.

**Comment by liuderchi** [comment]
@dino13 After several PR and experiments I successfully installed ide-yaml on my win 7 x64 machine.
Please upgrade ide-yaml with latest release.

**Comment by dino13** [comment]
Ok thanks, I search for ide-yaml or ide-yml but it doesn't show up anymore. Only one I can find is a language-yaml. Could that one be it?

**Comment by liuderchi** [comment]
@dino13 it should be `ide-yaml`
Please confirm you have Atom version > 1.21.

BTW What's result when you type following command in cmd.exe?
`ls .atom\packages\ide-yaml`

**Comment by dino13** [comment]
I have the latest version 1.21. I can't run that command in windows but I see that the package doesn't exist inb my packages directory and can't be found when searching.

**Comment by dino13** [comment]
I found it but get another error. The thing is I already have Git installed.

Failed to install ide-yaml because Git was not found.

The ide-yaml package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

You can install Git by downloading, installing, and launching GitHub for Windows: https://windows.github.com

Run apm -v after installing Git to see what version has been detected.

**Comment by liuderchi** [comment]
@dino13 Please upgrade again to 0.3.2.
This version require no external git dependency.

Does this solve this issue?

**Comment by dino13** [comment]
Looks like it worked. Thanks! So the git dependency wasn't recognizing?

**Comment by liuderchi** [comment]
> So the git dependency wasn't recognizing?

Very likely. Maybe the git was not added in system PATH.
Whatever the reason was now v0.3.2 can be installed without external git dependency. 🎉
